### ISSUE TITLE
Broken link in the README.md

### ISSUE THREAD

**Issue by samparent97** [EdwinFairchild/ELFInsight-VSCode#1]
This link seems like it either does not exist of brings me to a private repo: https://github.com/EdwinFairchild/ELFInsight

**Comment by EdwinFairchild** [comment]
Hey yeah I guess I forgot to update that , properly link to the repo to
file issues is this :
https://github.com/EdwinFairchild/ELFInsight-VSCode
Note the extension is not open source just yet

**Comment by EdwinFairchild** [comment]
yeah that link is to THIS repo, so clicking it would just be going in circles, though it should point to this repo i made it point to the private source code version. The code is not opensource yet.
